@startuml application_contest_module

skinparam ArrowColor #252525
skinparam ClassBackgroundColor #F0F1F5
skinparam ClassBorderColor #252525
skinparam ClassFontColor #252525


class PrismaExceptionHandler {
  + handleError(error: any)
}


class ApplicationContestRepository {
  - prisma: PrismaService
  + findFirst()
  + findUnique()
  + findMany()
  + create()
  + delete()
  + update()
}



class ApplicationContestService {
  - prismaExceptionHandler: PrismaExceptionHandler
  - applicationContestRepository: ApplicationContestRepository
  - contestRepository: ContestRepository
  + createApplicationContest(contestId: number, teamId: number, dto: CreateApplicationContestDto): Promise<ApplicationContestDto>
  + updateApplicationContestById(id: number, dto: UpdateApplicationContestDto): Promise<ApplicationContestDto>
  + deleteApplicationContestById(id: number): Promise<void>
  + getApplicationContests(): Promise<ApplicationContestDto[]>
  + getApplicationContestsByTeamId(teamId: number): Promise<ApplicationContestDto[]>
  + getApplicationContestsByContestId(contestId: number): Promise<ApplicationContestDto[]>
  
}

class ApplicationContestController {

  - contestService: ApplicationContestService
  + createApplicationContest(createApplicationContestDto: CreateApplicationContestDto): Promise<ApplicationContestDto>
  + updateApplicationContest(contestId: number, updateApplicationContestDto: UpdateApplicationContestDto): Promise<ApplicationContestDto>
  + deleteApplicationContestById(contestId: number): Promise<void>
  + getApplicationContest(): Promise<ApplicationContestDto[]>
  + getApplicationContestsByTeamId(teamId: number): Promise<ApplicationContestDto[]>
  + getApplicationContestsByContestId(contestId: number): Promise<ApplicationContestDto[]>
}
ApplicationContestRepository "1" *-- "1" PrismaService
ApplicationContestService "1" *-- "1" ApplicationContestRepository
ApplicationContestService "1" *-- "1" PrismaExceptionHandler
ApplicationContestController "1" *-- "1" ApplicationContestService

@enduml