@startuml project_module

skinparam ArrowColor #252525
skinparam ClassBackgroundColor #F0F1F5
skinparam ClassBorderColor #252525
skinparam ClassFontColor #252525


class ProjectRepository {
  - prisma: PrismaService
  + findFirst(): any
  + findUnique(): any
  + findMany(): any
  + create(): any
  + delete(): any
  + update(): any
}



class ProjectService {

  - prismaExceptionHandler: PrismaExceptionHandler
  - projectRepository: ProjectRepository
  + addProject(createProjectDto: CreateProjectDto): Promise<ProjectDto>
  + addCoverProject(projectId: number, file: File): Promise<CoverDto>
  + deleteCoverProject(projectId: number): Promise<void>
  + getProjects(): Promise<ProjectDto[]>
  + getProjectById(projectId: number): Promise<ProjectDto>
  + getProjectsByTeam(teamId: number): Promise<ProjectDto[]>
  + updateProjectById(projectId: number, dto: UpdateProjectDto): Promise<ProjectDto>
  + deleteProjectById(projectId: number): Promise<void>
}

class ProjectController {

  - projectService: UserService
  + addProject(createProjectDto: CreateProjectDto): Promise<ProjectDto>
  + addCoverProject(projectId: number, file: File): Promise<CoverDto>
  + deleteCoverProject(projectId: number): Promise<void>
  + getProjects(): Promise<ProjectDto[]>
  + getProjectById(projectId: number): Promise<ProjectDto[]>
  + getProjectsByTeam(teamId: number): Promise<ProjectDto[]>
  + editProjectById(projectId: number, editProjectDto: UpdateProjectDto): Promise<ProjectDto>
  + deleteProjectById(projectId: number): Promise<void>
}

ProjectController "1" *-- "1" ProjectService
ProjectController --> createException

ProjectService "1" *-- "1" ProjectRepository
@enduml

