@startuml research_paper

skinparam ArrowColor #252525
skinparam ClassBackgroundColor #F0F1F5
skinparam ClassBorderColor #252525
skinparam ClassFontColor #252525


class ResearchPaperRepository {
  - prisma: PrismaService
  + findFirst()
  + findUnique()
  + findMany()
  + create()
  + update()
  + delete()
}

class ResearchPaperController {

    - researchPaperService: ResearchPaperService
    + addResearchPaper(dto: CreateResearchPaperDto): Promise<ResearchPaperDto>
    + editResearchPaperById(researchPaperId: number, dto: UpdateResearchPaperDto): Promise<ResearchPaperDto>
    + deleteResearchPaper(researchPaperId: number): Promise<void>
    + findResearchPapers(page: number): Promise<ResearchPaperDto[]>
    + findResearchPapersByStatus(stauts: string): Promise<ResearchPaperDto[]>

}


class ResearchPaperService {
  - prismaExceptionHandler: PrismaExceptionHandler
  - researchPaperRepository: ResearchPaperRepository
  + createResearchPaper(dto: CreateResearchPaperDto): Promise<ResearchPaperDto>
  + updateResearchPaper(id: number, dto: UpdateResearchPaperDto): Promise<ResearchPaperDto>
  + deleteResearchPaperById(id: number): Promise<void>
  + findResearchPapers(page: number): Promise<ResearchPaperDto[]>
  + findResearchPapersByStatus(stauts: string): Promise<ResearchPaperDto[]>
}


ResearchPaperService "1" *-- "1" ResearchPaperRepository
ResearchPaperService "1" *-- "1" PrismaExceptionHandle
ResearchPaperRepository "1" *-- "1" PrismaService
ResearchPaperRepository "1" *-- "1" PrismaService
ResearchPaperService "1" *-- "1" ResearchPaperRepository
ResearchPaperController "1" *-- "1" ResearchPaperService
@enduml
